<h3><img src="<?= $this->url->dir() ?>plugins/Telegram/Asset/telegram-icon.png"/>&nbsp;Telegram</h3>
<?php if (empty($bot_name)): ?>
    <p class="alert alert-info">
      <?= t('Telegram bot is not configured in Kanboard settings.') ?><br/>
      <?= t('Go to ')?> <a href="<?= $this->url->href('ConfigController', 'integrations') ?>"> <?= t('Settings > Integrations > Telegram')?> </a>  <?= t(' and fill the form:')?> <br/>
      <?= t('Telegram bot username: Username of your Telegram Bot') ?><br/>
      <?= t('Telegram bot API key: HTTP API token generated by BotFather after bot creation') ?><br/>
    </p>
<?php else:?>
    <?php $random = md5(time().$this->url->base().rand());
          $bot_url="https://t.me/".$bot_name;
    ?>
    <p>
      <?= t('To get your Telegram chat id,')?><br/>
      <?= t('1. Send the message %s to',$random )?> <a href="<?= $bot_url ?>" target="_blank" rel="noreferrer"><?= $bot_url ?></a><br/>
      <?= t('2. Press')?><?= $this->modal->medium('none', t('Get chat id'), 'TelegramController', 'get_user_chat_id',array('plugin' => 'Telegram', 'private_message' => $random )) ?>
    </p>

    <div class="panel">
        <?= $this->form->label(t('Chat id of private chat with bot'), 'telegram_user_cid') ?>
        <?= $this->form->text('telegram_user_cid', $values) ?>

        <div class="form-actions">
            <input type="submit" value="<?= t('Save') ?>" class="btn btn-blue"/>
        </div>
    </div>
<?php endif?>
